spring:
  application:
    name: crossword-api
    client: ${CLIENT}

  # 데이터베이스 연결 설정
  datasource:
    # 💡 도커 컴포즈의 환경 변수 또는 로컬 env를 바라봅니다.
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT:3306}/${MYSQLDATABASE}?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLUSER}
    # 💡 GitHub Secrets에서 파생되어 도커 컴포즈가 넘겨줄 실제 운영 DB 비밀번호를 받습니다.
    password: ${MYSQLPASSWORD}

  # JPA 하이버네이트 설정
  jpa:
    hibernate:
      # 업데이트되면 
      ddl-auto: create
    properties:
      hibernate:
        # jpa가 수행한 쿼리를 SQL형식으로 터미널에 출력합니다 
        show_sql: true
        # 출력할 쿼리를 줄바꿈/들여쓰기해서 가독성을 높여줍니다
        format_sql: true
        # JPA에게 현재 우리 앱에서는 MySQL(방언)을 쓰고 있다고 알려줍니다.
        # JPA는 특정 DB에 종속되지 않으므로 이 정보가 필요합니다.
        dialect: org.hibernate.dialect.MySQLDialect

# 🚨 Swagger 관련 상세 설정 (기본 주소: http://localhost:8080/swagger-ui/index.html)
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs

# 2칸 들여쓰기 준수
server:
  servlet:
    context-path: /api
